project:
  output-dir: _site

format:
  revealjs: 
    theme: [white, slides.scss]
    slide-number: true
    default-image-extension: ""
    # navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    preview-links: auto
    reference-location: document
    footnotes-hover: true
    scrollable: true
    width: 1100
